#!/bin/bash

# automatize spawning an http server w/python

port=$1 # arg 

if [ -z "$1" ] # check if port is NULL 
then
	command python -m SimpleHTTPServer 80
else
	command python -m SimpleHTTPServer $port
fi

# ln -s /filepath/up /usr/local/bin  <- make binary global in system

# use case 1:
# up (runs on port 80)

# use case 2:
# up <port> (runs on specified port)
